name: MicroPython Unix CI

on: [push, pull_request]

jobs:
  micropython-unix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your code
        uses: actions/checkout@v3

      - name: Download prebuilt MicroPython Unix binary
        run: |
          curl -L -o micropython https://micropython.org/resources/code/micropython-unix-1.22.1-x86_64
          chmod +x micropython
          ./micropython -V  # verify it's working

      - name: Run MicroPython script
        run: ./micropython main.py
