name: MicroPython Unix CI

on: [push, pull_request]

jobs:
  micropython-unix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your code
        uses: actions/checkout@v3

      - name: Install Snap
        run: |
          sudo apt update
          sudo apt install snapd
          
      - name: Install micropython
        run: |
          sudo snap install micropython

      - name: Run MicroPython script
        run: micropython main.py
