name: Lint

on: [push]

jobs:
  ruff:
    runs-on: ubuntu-latest
    name: Lint with Ruff
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
        cache: 'pip'
    - name: Install Ruff
      run: pip install -r lib/requirements.txt
    - name: Run Ruff
      run: ruff check --output-format=github lib
    - name: Ruff main.py
      run: ruff check --output-format=github main.py
