name: Lint with pylint

on: [push]

jobs:
  ruff:
    runs-on: ubuntu-latest
    name: Lint with pylint
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: Install Pylint
      run: pip install pylint
    - name: pylint main.py
      run: pylint main.py 
